### PR TITLE
Use system service (fix ix-plugin-hub/iocage-plugin-index#287) 

### PR DESCRIPTION
**Pull request by jcassette**

### CODE REVIEW

**Review by sonicaj — COMMENTED** [review]
Thank you for the contribution @jcassette, can you please confirm if existing users are affected by this change once they update or is the transition smooth for them as well ?

**Comment by jcassette** [comment]
I have not tested an update of the plugin (and I don't know how I could do that).
I guess one would have to check that the permissions of the files used by the daemon are compatible with the user change.
Is it okay to recommend doing that with a message in `PLUGIN_INFO`?

**Review by sonicaj — APPROVED** [review]
Actually never mind, these changes are only relevant for fresh install. As after installation, a subsequent reboot of the plugin should have qbittorrent start with system service. Thanks for the contribution!

**Comment by jcassette** [comment]
Thank you 👍

**Pull request merged**
